window.CAP_LAB_DEFAULT_PRODUCTS = [
  {id:"01",name:"Gorra vintage bordada",category:"gorras",type:"cap",style:"Bordado",desc:"Silueta clásica con detalles gráficos y varias combinaciones de color.",badge:"VINTAGE",availability:"agotado",image:"../pinterest/caps/cap-01.jpg",imagePosition:"center 50%"},
  {id:"02",name:"Gorra negra clásica",category:"gorras",type:"cap",style:"Básica",desc:"Diseño limpio en negro para combinar con cualquier estilo.",badge:"CLÁSICA",image:"../pinterest/caps/cap-02.jpg"},
  {id:"03",name:"Gorra en varios colores",category:"gorras",type:"cap",style:"Color",desc:"Una selección de tonos para encontrar tu favorito.",badge:"COLOR",image:"../pinterest/caps/cap-03.jpg",imagePosition:"center 43%"},
  {id:"04",name:"Gorra pastel bicolor",category:"gorras",type:"cap",style:"Dos tonos",desc:"Base celeste con visera en contraste y parche frontal.",badge:"BICOLOR",image:"../pinterest/caps/cap-04.jpg"},
  {id:"05",name:"Gorra negra deportiva",category:"gorras",type:"cap",style:"Snapback",desc:"Perfil estructurado en negro con visera de color.",badge:"SNAPBACK",image:"../pinterest/caps/cap-05.jpg"},
  {id:"06",name:"Gorra roja deportiva",category:"gorras",type:"cap",style:"Snapback",desc:"Una opción intensa en rojo con acabado urbano.",badge:"URBANA",image:"../pinterest/caps/cap-06.jpg"},
  {id:"07",name:"Gorra blanca minimal",category:"gorras",type:"cap",style:"Minimal",desc:"Un básico claro, versátil y fácil de combinar.",badge:"MINIMAL",image:"../pinterest/caps/cap-07.jpg"},
  {id:"08",name:"Gorra azul bordada",category:"gorras",type:"cap",style:"Bordado",desc:"Azul profundo con un detalle gráfico al frente.",badge:"BORDADO",image:"../pinterest/caps/cap-08.jpg"},
  {id:"09",name:"Gorra negra gráfica",category:"gorras",type:"cap",style:"Gráfica",desc:"Acabado oscuro con bordados laterales y contraste sutil.",badge:"GRÁFICA",image:"../pinterest/caps/cap-09.jpg",imagePosition:"center 48%"},
  {id:"10",name:"Gorra beige urbana",category:"gorras",type:"cap",style:"Vintage",desc:"Tono neutro con bordado y detalles de inspiración retro.",badge:"VINTAGE",image:"../pinterest/caps/cap-10.jpg"},
  {id:"11",name:"Gorras deportivas duo",category:"gorras",type:"cap",style:"Color block",desc:"Combinación de dos estilos y colores llamativos.",badge:"DUO",image:"../pinterest/caps/cap-11.jpg"},
  {id:"12",name:"Gorra negra bordada",category:"gorras",type:"cap",style:"Bordado",desc:"Diseño oscuro con un bordado tono sobre tono.",badge:"DARK",image:"../pinterest/caps/cap-12.jpg"},
  {id:"13",name:"Gorras de colores",category:"gorras",type:"cap",style:"Colección",desc:"Distintos tonos y acabados para variar tu look.",badge:"COLECCIÓN",image:"../pinterest/caps/cap-13.jpg",imagePosition:"center 45%"},
  {id:"14",name:"Gorra azul clásica",category:"gorras",type:"cap",style:"Básica",desc:"Un perfil deportivo clásico en azul intenso.",badge:"CLÁSICA",image:"../pinterest/caps/cap-14.jpg"},
  {id:"15",name:"Gorra bordada street",category:"gorras",type:"cap",style:"Streetwear",desc:"Bordados gráficos sobre una silueta de inspiración urbana.",badge:"STREET",image:"../pinterest/caps/cap-15.jpg",imagePosition:"center 43%"},
  {id:"16",name:"Set de pines esmaltados",category:"pines",type:"pins",style:"Set",desc:"Motivos pequeños y coloridos para personalizar tus accesorios.",badge:"SET",image:"../pinterest/pins/pin-01.jpg",imagePosition:"center 47%"},
  {id:"17",name:"Pin ilustrado naranja",category:"pines",type:"pin",style:"Ilustrado",desc:"Un personaje esmaltado en tonos naranja y coral.",badge:"CORAL",image:"../pinterest/pins/pin-02.jpg"},
  {id:"18",name:"Dúo de pines ilustrados",category:"pines",type:"pins",style:"Dúo",desc:"Dos diseños esmaltados con ilustraciones de criaturas.",badge:"DÚO",image:"../pinterest/pins/pin-03.jpg"},
  {id:"19",name:"Pin cohete",category:"pines",type:"pin",style:"Espacial",desc:"Cohete esmaltado con detalles en azul y dorado.",badge:"ESPACIAL",image:"../pinterest/pins/pin-04.jpg"},
  {id:"20",name:"Pines de manzana",category:"pines",type:"pins",style:"Pop",desc:"Dos manzanas ilustradas en esmalte de colores.",badge:"POP",image:"../pinterest/pins/pin-05.jpg"},
  {id:"21",name:"Pines 9¾",category:"pines",type:"pins",style:"Numerado",desc:"Dos pines circulares con el número 9¾ y borde dorado.",badge:"9¾",image:"../pinterest/pins/pin-06.jpg"},
  {id:"22",name:"Set de pines geométricos",category:"pines",type:"pins",style:"Geométrico",desc:"Varios pines de formas y colores geométricos.",badge:"GEOMÉTRICO",image:"../pinterest/pins/pin-07.jpg"},
  {id:"23",name:"Set de pines rojos y negros",category:"pines",type:"pins",style:"Ilustrado",desc:"Colección de personajes ilustrados en rojo y negro.",badge:"ILUSTRADO",image:"../pinterest/pins/pin-08.jpg"},
  {id:"24",name:"Pin esmaltado oscuro",category:"pines",type:"pin",style:"Monocromo",desc:"Pin metálico en tonos oscuros con un diseño gráfico central.",badge:"MONOCROMO",image:"../pinterest/pins/pin-09.jpg"},
  {id:"25",name:"Pin búho en rama",category:"pines",type:"pin",style:"Naturaleza",desc:"Un búho blanco posado sobre una rama con detalles dorados.",badge:"NATURALEZA",image:"../pinterest/pins/pin-10.jpg"}
];
